# Regresión lineal en Python (ahora usando los paquetes de Python)
## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
from sklearn.feature_selection import RFE #Recursive Feature Elimination(RFE)
from sklearn.svm import SVR #svm=super vector machine..y SVR para llevar acabo el modelo lineal
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv("../datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"] #Columnas de prediccion, variables predictivas

In [4]:
X = data[feature_cols]
Y = data["Sales"] #variable a ser predecida

In [5]:
estimator = SVR(kernel="linear") #estimamos un modelo lineal
selector = RFE(estimator, 2, step=1) #me quiero quedar con 2 variables predictivas dentro del modelo, en 1 paso
selector = selector.fit(X,Y) #que cree el modelo con el X e Y que le indico

In [6]:
selector.support_ #para ver qué variables han sido seleccionadas y rechazadas

array([ True,  True, False])

In [7]:
selector.ranking_ #ranking de variables, las seleccionadas siempre dan 1, las rechazadas se ordenan en orden decreciente respecto a su significancia para el modelo

array([1, 1, 2])

In [8]:
from sklearn.linear_model import LinearRegression #para realizar la regresion lineal

In [9]:
X_pred = X[["TV", "Radio"]] #ya sabemos nuestras variables predictoras

In [10]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [11]:
lm.intercept_ #es la del corte con el eje x

2.9210999124051362

In [12]:
lm.coef_ #el coeficiente(pendiante)

array([0.04575482, 0.18799423])

In [13]:
lm.score(X_pred, Y) #Valor de R^2 ajustado

0.8971942610828956