# El método de k-means

In [1]:
import numpy as np

In [10]:
data = np.random.random(90).reshape(30,3)
data

array([[0.00791829, 0.58915332, 0.89087416],
       [0.34180403, 0.38500652, 0.56133012],
       [0.26407482, 0.0810057 , 0.54789802],
       [0.46060101, 0.65555716, 0.75262886],
       [0.01935071, 0.67948175, 0.68543854],
       [0.88059875, 0.15655558, 0.87040765],
       [0.06098595, 0.47203242, 0.83919132],
       [0.10530724, 0.94752185, 0.27228777],
       [0.32666616, 0.13339496, 0.81235633],
       [0.82978049, 0.65200579, 0.05951191],
       [0.70829938, 0.99463352, 0.87470032],
       [0.69562905, 0.33672325, 0.64531778],
       [0.4599799 , 0.18978278, 0.85618298],
       [0.39284559, 0.21730533, 0.33025359],
       [0.26533464, 0.38225062, 0.19859643],
       [0.24541375, 0.52672944, 0.04133565],
       [0.08475023, 0.6247758 , 0.49530102],
       [0.92139762, 0.81104404, 0.22257675],
       [0.43905912, 0.05802759, 0.44397185],
       [0.90899046, 0.28377429, 0.49357306],
       [0.43233398, 0.39859353, 0.212619  ],
       [0.88663903, 0.93831135, 0.47281389],
       [0.

**Vamos a elegir 2 centroides al azar. Que serán los 2 baricentros originales de los 2 clusters que generaremos**

In [19]:
c1 = np.random.choice(range(len(data))) 
c2 = np.random.choice(range(len(data)))
clust_centers = np.vstack([data[c1], data[c2]]) #con vstack los colocamos uno debajo del otro
clust_centers

array([[0.26407482, 0.0810057 , 0.54789802],
       [0.39284559, 0.21730533, 0.33025359]])

### **Primera forma:** 

In [4]:
from scipy.cluster.vq import vq

In [13]:
clusters = vq(data, clust_centers) #le indicamos los datos y los centros par generar los clusters
clusters

(array([1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0,
        1, 0, 1, 1, 0, 1, 0, 1], dtype=int32),
 array([0.81712828, 0.36075855, 0.20481247, 0.58288485, 0.78782396,
        0.62170129, 0.68595755, 0.80670622, 0.39245324, 0.50598645,
        0.44327183, 0.42899835, 0.43326104, 0.20108935, 0.44216497,
        0.64753058, 0.6703529 , 0.2828847 , 0.        , 0.52369582,
        0.41176999, 0.        , 0.27869853, 0.41042729, 0.33064292,
        0.51864724, 0.78140236, 0.5931407 , 0.6069311 , 0.6236119 ]))

* El primer Array nos da la informacion de a qué cluster pertenece cada una de las observaciones.
* El segundo array nos da la distancia de cada una de las 30 observaciones hasta el baricentro, según el cluster en el cual se encuentra.

In [6]:
labels = clusters[0]
labels

array([0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0], dtype=int32)

In [14]:
import chart_studio.plotly as py
import plotly.graph_objs as go

import plotly.offline as ply

In [20]:
x = []
y = []
z = []
x2 = []
y2 = []
z2 = []

for i in range(0, len(labels)):
    if(labels[i] == 0):
        x.append(data[i,0])
        y.append(data[i,1])
        z.append(data[i,2])
        
    else:
        x2.append(data[i,0])
        y2.append(data[i,1])
        z2.append(data[i,2])

cluster1 = go.Scatter3d(
    x=x,
    y=y,
    z=z,
    mode='markers',
    marker=dict(
        size=12,
        line=dict(
            color='rgba(217, 217, 217, 0.14)',
            width=0.5
        ),
        opacity=0.9
    ),
    name="Cluster 0"
)


cluster2 = go.Scatter3d(
    x=x2,
    y=y2,
    z=z2,
    mode='markers',
    marker=dict(
        color='rgb(127, 127, 127)',
        size=12,
        symbol='circle',
        line=dict(
            color='rgb(204, 204, 204)',
            width=1
        ),
        opacity=0.9
    ),
    name="Cluster 1"
)
data2 = [cluster1, cluster2]
layout = go.Layout(
    margin=dict(
        l=0,
        r=0,
        b=0,
        t=30
    )
)

fig = go.Figure(data=data2, layout=layout)
ply.plot(fig, filename='Clusters')


/home/david/anaconda3/lib/python3.7/site-packages/plotly/offline/offline.py:562: UserWarning:

Your filename `Clusters` didn't end with .html. Adding .html to the end of your file.



'Clusters.html'

### **Segunda forma:**

In [16]:
from scipy.cluster.vq import kmeans

In [24]:
kmeans(data, clust_centers) #nos da la info de los baricentros, 

(array([[0.25356775, 0.33343472, 0.61008505],
        [0.61225214, 0.67847808, 0.45417067]]), 0.3953435194154305)

* El tercer numero del array que da kmeans es el valor de la suma de los cuadrados de los errores normalizado (ver video teoria anterior). De cada uno de los puntos resta la distancia de dichos puntos al baricentro, las eleva al cuadrado, las suma todas ellas, y las divide la suma total de los resultados, dividida entre la suma de los cuadrados en cada punto al baricentro global del sistema(de absolutamente todos los puntos del data).

In [25]:
kmeans(data, 2) #también podemos darle solo el numero de clusters que queremos, 2 en este caso, en vez de los centroides

(array([[0.21991345, 0.4151696 , 0.50781939],
        [0.78716605, 0.61852133, 0.61192767]]), 0.3779717903498595)